### PR TITLE
Rebase develop onto master

### PR DESCRIPTION
**Pull request by thoelze1**
People are having issues working on `develop` because it lacks bug fixes from `master`, so I rebased

### CODE REVIEW

**Comment by thoelze1** [comment]
I have never made a PR of this size. Could someone please confirm that it looks reasonable? All I did was:

- Rebased my local copy of develop (which pointed to the same commit as david-janssen:develop) onto my local copy of master (which pointed to the same commit as david-janssen:master)
- Manually resolved 2 small conflicts
- Pushed to thoelze1:develop
- PR'd from thoelze1:develop to david-janssen:develop
- Noticed merge conflicts between the two branches. Why did this happen?
- Merged david-janssen:develop into thoelze1:develop
- PR no longer has merge conflicts

Thanks

**Comment by bard** [comment]
You'll want to merge rather than rebase, otherwise everyone's local copy of
develop becomes invalid.

>

**Comment by slotThe** [comment]
On Tue, Feb 23 2021 21:38, Massimiliano Mirra wrote:

> You'll want to merge rather than rebase, otherwise everyone's local
> copy of develop becomes invalid.

If we merge we'll probably get a very ugly history once we merge develop
back into master before a release.  I suppose we could say that develop
is for developers anyways and they should probably be able to deal with
this themselves?  Maybe the history mangling will not be that bad?  I
don't know; I love diverging branches.

**Comment by bard** [comment]
I usually prefer the log to reflect actual development (if a branch has diverged for some time, I wouldn't want to erase that information) and haven't so far reaped benefits from a neater-looking branch diagram on projects with just two or three long-running branches, but if that's important, and those who are working on develop can and want to handle a rewritten history, sure, go for it.

**Comment by bard** [comment]
Just for reference, this is how it looks like:

Screenshot from 2021-02-24 08-38-30

**Comment by slotThe** [comment]
Sigh, every time I look at this I'm reminded how much easier things would be if we just developed everything on a single branch.  After all, we do have release tags, so if people are really interested in looking up documentation or features for the version they are using it should be as simple as switching the repo back to that commit...

**Comment by bard** [comment]
@slotThe I think you're 100% right. Potentially destabilizing WIP work can always go into relatively short-lived feature branches. Just an outsider's opinion but there's often so much mental effort that goes into this kind of overhead that could go into actual code. /cc @david-janssen

**Comment by thoelze1** [comment]
Sounds like a good idea to me. I like @bard's point about mental effort. That being said, I have limited experience with managing codebases. But I trust your opinions, especially given that it was @slotThe who proposed the contributing guidelines (#147) in the first place.

**Comment by david-janssen** [comment]
Hey everyone,

Back from the sort-of-dead for an indefinite amount of time. I am 100% behind just making this a 1-branch project. I was sort of planning a very large refactor of certain elements of the codebase. First I wanted to really redo the IO-shell. Currently we are really mixing the logical aspects of what we want the App to do with the IO aspects of how we do this. This is simply because I wasn't very good at Haskell when I designed this in the first place.  Another reason to look again at the IO shell is because at the moment parsing and command-line handling is a conceptual mess, and it's wonders that it works.

After getting the IO-aspects really cleaned up, I was actually hoping to really redo the way we handle how we specify buttons. Currently every button is a little IO-machine that does things like register hooks and deal with timers. I've spent some time behind the screens experimenting with more algebraic ways of defining buttons as simple filters on pure lists. I haven't gotten that 100% working yet, but I find some of the ideas promising.

However, I reallllly need you guys' input here: what is the best way for us to transition from this interesting mess of a project to a slightly more organized, straightforward way of managing the codebase? And if we do have a 1-branch way of keeping track, how do we deal with "David wants to do another crazy refactor" type scenarios?

If you think it's a good idea to make a professional, 1-branch, gradual-update style system, I would also be very happy to support this, and I can go and be a crazy hermit on my own mountain, and occasionally come along with wild ideas that you either accept or reject. I am probably better at being a crazy hermit than a responsible manager anyways.

So: you have my full backing of your intentions, I am happy to help however I can, but I need direction myself, because I have no idea what the best way to organize something like this is.

**Comment by molleweide** [comment]
Nice to hear that you are getting better David! Or did you mean that you are actually fully restored?

It is very interesting to read and try to follow the discussion. i'm trying to learn haskell so I can participate sometime soon. I like the single branch philosophy but I am no git pro.

**Comment by david-janssen** [comment]
Hey there @molleweide

Not fully restored at all, but restored enough to do something productive :-). If you ever need any help learning haskell, feel free to ask me any questions. I am also 100% autodidact when it comes to Haskell, so I know the struggle.

In regards to merging everything up, I just forked the `develop` branch into a new branch intelligently named `merging` and merged `master` into it. I had to delete break the Mac support, because I don't know how `kcMap` works. But on Linux this new branch (after fixing some conflicts) compiles and runs my testing map.

Now I am going to make some changes to it, namely, add in the cross-platform keycode support that I have been working on. Additionally I will reorganize some of the code. I will also keep trying to pull in updates from master and develop. Then, once all is good, we should put it all into `master` and get used to living a 1-branch life.

**Comment by molleweide** [comment]
> Not fully restored at all, but restored enough to do something productive :-). If you ever need any help learning haskell, feel free to ask me any questions. I am also 100% autodidact when it comes to Haskell, so I know the struggle.

Allright nice!! Ima do some more reading and then I'll get back to you.

**Comment by thoelze1** [comment]
Hey David! Happy to hear you're somewhat better!

Your ideas for refactoring sound great to me. I think the best way of moving forward is closing this rebase PR and creating a similar PR that merges `develop` onto `master` instead of rebasing. At that point you can create a branch for your refactors and I can work on mac support, and anyone else can make a feature branch of their own.

> And if we do have a 1-branch way of keeping track, how do we deal with "David wants to do another crazy refactor" type scenarios?

You could create a crazy-refactor branch off of our single main branch, and rebase from time to time or before merging? Perhaps there are issues with this that I don't see...

> I have no idea what the best way to organize something like this is.

I have no idea if this is the best way of moving forward, but maybe it's a reasonable way of reaching a single-branch state and then getting the existing fixes/features through the pipeline. What do you think?

**Comment by david-janssen** [comment]
> I think the best way of moving forward is closing this rebase PR and creating a similar PR that merges develop onto master instead of rebasing.

Wish granted. #226

> I have no idea if this is the best way of moving forward, but maybe it's a reasonable way of reaching a single-branch state and then getting the existing fixes/features through the pipeline. What do you think?

I have no idea, but it sounds plausible, so let's give it a shot.

**Pull request closed without merging**
