### PR TITLE
Unification

### PR DESCRIPTION
**Pull request by david-janssen**
Continuation of #191, but instead of rebasing we are merging.

I have no idea what I am doing, gitwise, but this is a merge of develop into master. There are currently merging conflicts.

Ideally I would just have my own branch of master on my own fork of kmonad, but my fork of kmonad is the official one, which means I needed a branch which I've called master-merged. It will contain the 'unified' master and develop. Once it's down, we'll merge it into master and delete both 'master-merged' and 'develop'.

I am not sure if this is the best way of doing things, but sometimes a-way-that-might-work is better than the-best-way-i-do-not-know-yet.

### CODE REVIEW

**Comment by david-janssen** [comment]
So, to unify develop and master I need to fix the keycode representations. This has broken mac-support. I have started adding in code that deals with these issues, but we are not there yet. When I have brought this branch up to the point where keycode has been well-done I will put a notification in this PR and boop the people involved so we can get mac-support back up.

**Comment by molleweide** [comment]
Allright!

**Comment by MaxGyver83** [comment]
> So, to unify develop and master I need to fix the keycode representations. This has broken mac-support. I have started adding in code that deals with these issues, but we are not there yet. When I have brought this branch up to the point where keycode has been well-done I will put a notification in this PR and boop the people involved so we can get mac-support back up.

Does this by chance also address this issue? https://github.com/david-janssen/kmonad/issues/135#issuecomment-741809884

**Comment by thoelze1** [comment]
I was able to rebase develop onto master without fixing keycode representations and without breaking Mac support (see [this comment](https://github.com/david-janssen/kmonad/pull/191#issuecomment-784640771)). I'm going to reattempt this shortly (merging instead of rebasing) and make a PR. Then we will be back to a single branch at which point you can make a feature branch and add your keycode refactoring commits, and I can concurrently make a branch and add my commits supporting the latest Mac version.

**Comment by david-janssen** [comment]
@MaxGyver83 It doesn't address it just yet. First we get to 1 branch. Then the keycode refactor will move a little bit of the keycode management responsibilities to the OSes, at which point it should be easier to address #135 in some windows-specific code.

@thoelze1 Ahhh, ok. I didn't feel confident with the Mac-stuff. Thanks for doing this :-)

@bard Thanks for the advice :-) I think we have something of a solution moving now, which I will keep moving forward with, but I will keep this in mind for the future. I think the core issue is that my git knowledge doesn't go much further than pull commit push and a bit of merge. Even rebase I start thinking.. Que?

**Pull request closed without merging**
