### PR TITLE
Mac bug fix and documentation improvements

### PR DESCRIPTION
**Pull request by thoelze1**
1. Add bug fix (#86) from @agile-jordi
2. Improve macOS documentation

### CODE REVIEW

**Comment by focusaurus** [comment]
Just a note with this fix and the associated issue comments and docs I am able to get kmonad running on mac, at least ostensibly. I have not gotten it to work yet though. Only output I see is `IORegistryEntryCreateCFProperty error`.

**Comment by agile-jordi** [comment]
@focusaurus Maybe you can open an issue. There I will try to help with what I did to diagnose the issue in my case.

**Comment by thoelze1** [comment]
@focusaurus that error should be harmless - try running with `-l debug` and type a bit to see if kmonad is working

**Comment by david-janssen** [comment]
Merged with the usual Mac-caveat: I hope you know what you're doing because I don't :-)

**Pull request merged**
