### PR TITLE
static build: Add workaround for nh2/static-haskell-nix#53

### PR DESCRIPTION
**Pull request by nh2**
See https://github.com/nh2/static-haskell-nix/issues/53

### CODE REVIEW

**Comment by david-janssen** [comment]
Thank you very much for this fix. I tried it and compilation is currently running. I have the sneaking suspicion this might take ages, and I'll let you know if it works out or not when it finishes, but I already merged this pull request, because it certainly got past the issue that I was having.

**Comment by nh2** [comment]
> I have the sneaking suspicion this might take ages

In case you haven't already, enabling the `static-haskell-nix` binary cache (https://github.com/nh2/static-haskell-nix/#binary-caches-for-faster-building-optional) will ensure you don't have to build big things like GHC from scratch, only those packages from your `lts-14.7` that the binary cache hasn't built yet.

**Comment by david-janssen** [comment]
Ooooh, great tip. I missed that. Added cachix and restarted compilation. I think I was trying to build multiple versions of ghc :-)

**Comment by david-janssen** [comment]
Yeah, that finished and took no time at all. Additionally, I can easily run the binary in my own NixOS setup, or in an Ubuntu virtualbox.

**Pull request merged**
