### PR TITLE
Add runit service

### PR DESCRIPTION
**Pull request by slotThe**
Now that we have a systemd unit, I can't let runit fall behind!

Also mention the startup scripts in the `README.md`, because it feels like something that we should do

### CODE REVIEW

**Comment by slotThe** [comment]
It's a tiny shell script (can't really butcher something so short) and I think the doc improvement is a net-positive, so I will merge this in a few days if there are now objections

**Comment by david-janssen** [comment]
This is great. Could you add an entry to the changelog? Then we'll merge this in right away.

**Comment by slotThe** [comment]
On Sun, Feb 07 2021 23:56, David Janssen wrote:
> This is great. Could you add an entry to the changelog? Then we'll
> merge this in right away.

Ah good point, it's done.  I also added a note for the systemd unit, as
that was forgotten in the respective pr as well.

**Comment by david-janssen** [comment]
Perfect!

**Pull request merged**
