### PR TITLE
Fixed ISO key

### PR DESCRIPTION
**Pull request by precondition**
Fixes issue #113 

As I've written in the comments of that issue, `KeyIso` is mapped to `<I178>` in Linux which produces absolutely nothing. Not even `NoSymbol` is assigned to it. That keycode has no HID equivalent. I guess `fallthrough` fooled me into thinking it works when I submitted PR #88

### CODE REVIEW

**Comment by david-janssen** [comment]
Hey there,

Sorry for the late reply, things have been hectic. I am happy to pull the personal keymap change you made, but I don't think it is a good idea to make `iso` an alias for `102d`. If `KeyIso` isn't mapped to anything in X11, that's fine, but the name exists in the linux-headers, so 'KEY_ISO' is a thing, and I'd rather avoid the confusion. This is all *unless* you have a keyboard with actual ink on the key saying 'iso', in which case I'm happy to come up with some solution that takes this into account

If you could alter your pull-request, then I'd be happy to merge.

Cheerio,

D

**Comment by precondition** [comment]
I doubt any keyboard has a key with "iso" written on it but that's generally how it is referred to in discussions.

What about `lsgt` as used in `xkbd` files or `nubs` as used in QMK? I'm not really a fan of the `102d` notation.

**Comment by slotThe** [comment]
I have to say I quite like `102nd`, but the truth is that most 100% ISO
keyboards today do not have 102 keys anymore (having 105 instead) and so
the name may be nothing more than historical baggage at this point.

On Mon, Oct 12 2020 07:16, precondition wrote:
> What about `lsgt` as used in `xkbd` files or `nubs` as used in QMK?

I think both of those would work very nicely as aliases.

**Comment by precondition** [comment]
> On Mon, Oct 12 2020 07:16, precondition wrote: What about `lsgt` as used in `xkbd` files or `nubs` as used in QMK?
> I think both of those would work very nicely as aliases.

Now that I think about it, it is true that nothing stops me from adding both

**Comment by david-janssen** [comment]
Yeah, I'm absolutely fine with both `lsgt` and `nubs`, it's just that `iso` creates a semantic conflict with the Linux-headers we are mirroring that I would really like to avoid.

**Comment by david-janssen** [comment]
Perfect! Thanks :)

**Pull request merged**
